name: Doxygen GitHub Pages Deploy Action Producer C SDK

on:
  push:
    branches:
      - doxygen-ga-develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
      - name: Generate Doxygen Documentation
        run: doxygen
        shell: bash
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: doc
          branch: gh-pages